### ISSUE TITLE
use lazyload in img

### ISSUE THREAD

**Issue by alirezaseif28** [scott-little/lazyload#3]
hi.
Is this process done by putting the loading="lazy" in the image tag or needing implementations?
thanks.

**Comment by coliff** [comment]
Yes - it explains that on the `README.md`.
https://github.com/scott-little/lazyload#set-loadinglazy-on-an-imageiframe

If you have Chrome Canary (v75) and have the required flags enabled then check: https://mathiasbynens.be/demo/img-loading-lazy for a demo.

**Comment by alirezaseif28** [comment]
thank you @coliff
